import Head from "next/head";
// import ColourBlock from "@/sections/colourBlock";
import TextBlock from "@/sections/textBlock";
import Hero from "@/sections/hero";
import TextTicker from "@/sections/textTicker";
import Slider from "@/sections/slider";
import Footer from "@/sections/footer";
import TextImageBlock from "@/sections/textImageBlock";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <ColourBlock page={'home'} /> */}
        <Hero page={"home"} />
        <TextTicker page={"home"} />
        <TextBlock page={"home"} />
        <Slider page={"home"} />
        <TextImageBlock page={"home"} />
        <Footer page={"home"} />
      </main>
    </>
  );
}
