import Head from "next/head";
import { getPageData } from "@/sanity/queries/fragments/pages";

import Hero from "@/sections/hero";
import Sections from "@/components/sections";

// Hardcoded sections kept as fallback during migration to Sanity-driven sections.
// Remove each one as its CMS schema + section type is added.
import TextBlock from "@/sections/textBlock";
import TextTicker from "@/sections/textTicker";
import Slider from "@/sections/slider";
import Footer from "@/sections/footer";

type HomePage = {
  _id?: string;
  hero?: {
    tag?: string;
    title?: string;
    version?: string;
    scrollLabel?: string;
  };
  sections?: Array<{ _key: string; _type: string; [key: string]: any }>;
  seo?: {
    title?: string;
    description?: string;
    media?: any;
  };
};

interface HomeProps {
  page: HomePage | null;
}

export default function Home({ page }: HomeProps) {
  return (
    <>
      <Head>
        <title>{page?.seo?.title || "Create Next App"}</title>
        <meta
          name="description"
          content={page?.seo?.description || "Generated by create next app"}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero page="home" hero={page?.hero} />

        {/* Migration fallback — remove each as its CMS section type lands */}
        <TextTicker page="home" />
        <TextBlock page="home" />
        <Slider page="home" />
        <Sections page={page ?? undefined} />

        <Footer page="home" />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const page = (await getPageData("homePage")) as HomePage | null;

  return {
    props: {
      id: "home",
      page,
    },
    revalidate: 60,
  };
}
